org: lonedev
app: languvi
service: notification-service
frameworkVersion: "3"

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: 
    REGION: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail 
          Resource: arn:aws:ses:*

resources: 
  Resources:  
    MailQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ${self:custom.mailQueue.name}
  Outputs:
    MailQueueArn:
      Value: ${self:custom.mailQueue.arn}
      Export:
        Name: ${self:custom.mailQueue.name}-Arn
    MailQueueUrl:
      Value: ${self:custom.mailQueue.url}
      Export:
        Name: ${self:custom.mailQueue.name}-Url

functions: 
  sendMail:
    handler: src/sendmail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1


custom: 
  mailQueue: 
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  bundle:
    linting: false